-- MySQL Script generated by MySQL Workbench
-- 05/12/23 20:31:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema centromedico
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `centromedico` ;

-- -----------------------------------------------------
-- Schema centromedico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `centromedico` DEFAULT CHARACTER SET latin1 ;
USE `centromedico` ;

-- -----------------------------------------------------
-- Table `centromedico`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `centromedico`.`roles` ;

CREATE TABLE IF NOT EXISTS `centromedico`.`roles` (
  `id_rol` INT(11) NOT NULL,
  `nombre_rol` TEXT NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `centromedico`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `centromedico`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `centromedico`.`usuarios` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `usuLogin` CHAR(15) CHARACTER SET 'utf8' NOT NULL,
  `usuPassword` VARCHAR(60) CHARACTER SET 'utf8' NOT NULL,
  `usuEstado` ENUM('Activo', 'Inactivo') CHARACTER SET 'utf8' NOT NULL,
  `usuRol` TEXT CHARACTER SET 'utf8' NOT NULL,
  `roles_id_rol` INT(11) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `login` (`usuLogin` ASC),
  INDEX `fk_usuarios_roles1_idx` (`roles_id_rol` ASC),
  CONSTRAINT `fk_usuarios_roles1`
    FOREIGN KEY (`roles_id_rol`)
    REFERENCES `centromedico`.`roles` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `centromedico`.`medicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `centromedico`.`medicos` ;

CREATE TABLE IF NOT EXISTS `centromedico`.`medicos` (
  `idMedico` INT(11) NOT NULL AUTO_INCREMENT,
  `medIdentificacion` CHAR(15) CHARACTER SET 'utf8' NOT NULL,
  `medNombres` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `medApellidos` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `medEspecialidad` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `medTelefono` CHAR(15) CHARACTER SET 'utf8' NOT NULL,
  `medCorreo` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `usuarios_idUsuario` INT(11) NOT NULL,
  PRIMARY KEY (`idMedico`),
  UNIQUE INDEX `medIdentificacion` (`medIdentificacion` ASC),
  INDEX `fk_medicos_usuarios1_idx` (`usuarios_idUsuario` ASC),
  CONSTRAINT `fk_medicos_usuarios1`
    FOREIGN KEY (`usuarios_idUsuario`)
    REFERENCES `centromedico`.`usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 47
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `centromedico`.`pacientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `centromedico`.`pacientes` ;

CREATE TABLE IF NOT EXISTS `centromedico`.`pacientes` (
  `idPaciente` INT(11) NOT NULL AUTO_INCREMENT,
  `pacIdentificacion` CHAR(15) CHARACTER SET 'utf8' NOT NULL,
  `pacNombres` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `pacApellidos` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `pacFechaNacimiento` DATE NOT NULL,
  `pacSexo` ENUM('Femenino', 'Masculino') CHARACTER SET 'utf8' NOT NULL,
  `usuarios_idUsuario` INT(11) NOT NULL,
  PRIMARY KEY (`idPaciente`),
  UNIQUE INDEX `pacIdentificacion` (`pacIdentificacion` ASC),
  INDEX `fk_pacientes_usuarios1_idx` (`usuarios_idUsuario` ASC),
  CONSTRAINT `fk_pacientes_usuarios1`
    FOREIGN KEY (`usuarios_idUsuario`)
    REFERENCES `centromedico`.`usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `centromedico`.`consultorios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `centromedico`.`consultorios` ;

CREATE TABLE IF NOT EXISTS `centromedico`.`consultorios` (
  `idConsultorio` INT(11) NOT NULL,
  `conNombre` CHAR(15) NOT NULL,
  PRIMARY KEY (`idConsultorio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centromedico`.`citas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `centromedico`.`citas` ;

CREATE TABLE IF NOT EXISTS `centromedico`.`citas` (
  `idCita` INT(11) NOT NULL AUTO_INCREMENT,
  `citFecha` DATE NOT NULL,
  `citHora` TIME NOT NULL,
  `citPaciente` INT(11) NOT NULL,
  `citMedico` INT(11) NOT NULL,
  `citConsultorio` INT(11) NOT NULL,
  `citEstado` ENUM('Asignado', 'Atendido') CHARACTER SET 'utf8' NOT NULL DEFAULT 'Asignado',
  `citObservaciones` TEXT CHARACTER SET 'utf8' NOT NULL,
  `consultorios_idConsultorio` INT(11) NOT NULL,
  PRIMARY KEY (`idCita`),
  INDEX `fk_paciente` (`citPaciente` ASC),
  INDEX `fk_medico` (`citMedico` ASC),
  INDEX `fk_citas_consultorios1_idx` (`consultorios_idConsultorio` ASC),
  CONSTRAINT `fk_medicos_idMedico`
    FOREIGN KEY (`citMedico`)
    REFERENCES `centromedico`.`medicos` (`idMedico`),
  CONSTRAINT `fk_pacientes_idPaciente`
    FOREIGN KEY (`citPaciente`)
    REFERENCES `centromedico`.`pacientes` (`idPaciente`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_citas_consultorios1`
    FOREIGN KEY (`consultorios_idConsultorio`)
    REFERENCES `centromedico`.`consultorios` (`idConsultorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
